[tool.black]
line-length = 99
skip-numeric-underscore-normalization = 1
exclude = '(node_modules)'

[tool.isort]
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
default_section = "THIRDPARTY"
use_parentheses = "True"
line_length = 99
skip_glob="**/node_modules/*"
src_paths = ""
